plugin: amazon.aws.aws_ec2

regions:
  - us-west-2

filters:
  tag:Name: app_server
  instance-state-name: running

hostnames:
  - private-ip-address

# Don't crash if no matching instances are found
strict: False

# Create groups of the form "tag_<Name value>" - useful for large numbers of instances
keyed_groups:
  - key: tags.Name
    prefix: tag

compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu
  ansible_ssh_common_args: >
    -o ProxyCommand="ssh -i {{ playbook_dir }}/devops_practice.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ bastion_ip }}"
