name: Terraform Plan

on:
  pull_request:
    branches: ['main', 'prod']
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      version_tag:
        description: 'Git branch or tag name (e.g. main or v1.0.2)'
        required: false

permissions:
  contents: read
  pull-requests: write

env:
  TF_WORKING_DIR: terraform/environments/${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || (github.base_ref == 'prod' && 'prod' || 'dev') }}

jobs:
  validate_plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.env || (github.base_ref == 'prod' && 'prod' || 'dev') }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_analytics_db_password: ${{ secrets.DB_ANALYTICS_PASSWORD }}

    steps:
      - name: Show selected environment
        run: |
          echo "Using environment: ${{ env.TF_WORKING_DIR }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag || 'main' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -no-color | tee plan.txt

      - name: Post plan as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync(`${process.env.TF_WORKING_DIR}/plan.txt`, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📦 Terraform Plan Output\n\n\`\`\`hcl\n${plan}\n\`\`\``
            });
